import sys, os
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from database import SessionLocal, engine, Base
from models import Module, ModuleContent, Quiz, Question, LevelEnum, Course

db = SessionLocal()

def get_course_id(code: str) -> int:
    course = db.query(Course).filter(Course.code == code).first()
    return course.id if course else None

def patch():
    print("🔧 Patching OS and SE courses with content and quizzes...")

    os_id = get_course_id("CSC 320")
    se_id = get_course_id("CSC 340")

    if not os_id or not se_id:
        print("❌ Courses not found. Run seed first.")
        return

    # ── OS modules content ─────────────────────────────
    os_modules_data = [
        {
            "title": "OS Overview",
            "content": {
                LevelEnum.foundational: ("What is an Operating System?", "An operating system (OS) is system software that manages computer hardware, software resources, and provides common services for computer programs. It acts as an intermediary between users and the computer hardware.\n\nThe OS performs several key functions: process management, memory management, file system management, device management, and security. Without an OS, each application would need to include its own drivers for every possible hardware configuration.\n\nExamples of modern operating systems include Windows, macOS, Linux, Android, and iOS. Each is designed for different use cases — desktop computing, mobile devices, servers, or embedded systems.\n\nThe kernel is the core of the OS that has complete control over everything in the system. It manages low-level hardware operations while higher-level components provide user interfaces and application support."),
                LevelEnum.intermediate: ("OS Architecture and System Calls", "Operating systems are structured in layers. The hardware sits at the bottom, then the kernel, then system libraries, then applications. This separation ensures stability and security.\n\nSystem calls are the programming interface between applications and the OS kernel. When a program needs to read a file, allocate memory, or create a process, it makes a system call. Examples: read(), write(), fork(), exec(), malloc().\n\nMonolithic kernels (Linux, Windows) run all OS services in kernel space for performance. Microkernels (Mach, QNX) run most services in user space for reliability. Hybrid kernels combine both approaches.\n\nKernel mode vs User mode: Hardware enforces two privilege levels. Kernel mode has unrestricted access to all hardware. User mode is restricted — applications must use system calls to access privileged operations. This separation prevents buggy programs from crashing the entire system."),
                LevelEnum.advanced: ("OS Design Principles and Modern Trends", "Modern OS design principles include abstraction (hiding hardware complexity), resource sharing (multiple programs share CPU, memory), isolation (protecting processes from each other), and portability (running on different hardware).\n\nVirtual machines allow multiple OS instances to run on one physical machine using a hypervisor. Type 1 hypervisors (VMware ESXi, Xen) run directly on hardware. Type 2 hypervisors (VirtualBox, VMware Workstation) run on top of a host OS.\n\nContainerization (Docker, Kubernetes) provides OS-level virtualization. Containers share the host OS kernel but have isolated user spaces. Much lighter than VMs — start in milliseconds, use megabytes not gigabytes.\n\nReal-time operating systems (RTOS) guarantee response times for critical operations. Used in automotive systems, medical devices, industrial control. Hard RTOS: missing a deadline is catastrophic. Soft RTOS: missing a deadline degrades performance."),
            },
            "quiz": [
                {"text": "What is the primary role of an operating system?", "option_a": "To run applications", "option_b": "To manage hardware and software resources", "option_c": "To provide internet access", "option_d": "To store user data", "correct": "B", "explanation": "An OS acts as an intermediary between users and hardware, managing all system resources."},
                {"text": "What is the kernel?", "option_a": "A user application", "option_b": "A type of memory", "option_c": "The core of the OS with full hardware control", "option_d": "A file system", "correct": "C", "explanation": "The kernel is the core component of an OS that has complete control over all hardware in the system."},
                {"text": "What are system calls?", "option_a": "Phone calls between servers", "option_b": "Programming interface between applications and kernel", "option_c": "Network protocols", "option_d": "Hardware interrupts", "correct": "B", "explanation": "System calls provide the interface through which user programs request services from the kernel."},
                {"text": "Which privilege level has unrestricted hardware access?", "option_a": "User mode", "option_b": "Application mode", "option_c": "Safe mode", "option_d": "Kernel mode", "correct": "D", "explanation": "Kernel mode has unrestricted access to all hardware. User mode is restricted to prevent applications from crashing the system."},
                {"text": "What is a Type 1 hypervisor?", "option_a": "Runs on top of a host OS", "option_b": "Runs directly on hardware", "option_c": "A container runtime", "option_d": "A file system type", "correct": "B", "explanation": "Type 1 (bare metal) hypervisors run directly on hardware without a host OS. Examples: VMware ESXi, Xen."},
            ]
        },
        {
            "title": "Process Management",
            "content": {
                LevelEnum.foundational: ("What is a Process?", "A process is a program in execution. When you run a program, the OS creates a process that includes the program code, its current activity (program counter), and a stack. Multiple instances of the same program can run as separate processes.\n\nA process has several states: New (being created), Ready (waiting for CPU), Running (executing), Waiting (waiting for I/O), and Terminated (finished). The OS scheduler moves processes between these states.\n\nThe Process Control Block (PCB) stores all information about a process: process ID, state, program counter, registers, memory limits, open files, and scheduling information. The OS maintains a PCB for every process.\n\nProcess creation: A parent process creates child processes using system calls (fork() in Unix). The child is a copy of the parent. exec() replaces the process image with a new program."),
                LevelEnum.intermediate: ("Process Scheduling and Context Switching", "The CPU scheduler selects which ready process gets the CPU next. Scheduling algorithms balance fairness, throughput, and response time.\n\nContext switching is saving the state of the current process and loading the state of the next process. The PCB stores all register values, program counter, and memory maps. Context switches are overhead — they take time without doing useful work.\n\nInter-Process Communication (IPC): Processes need to communicate and synchronize. Methods include shared memory (fast but requires synchronization), message passing (send/receive), pipes (unidirectional data flow), and signals (asynchronous notifications).\n\nProcess vs Thread: A process has its own memory space. Threads within the same process share memory and resources but have separate stacks and registers. Threads are lighter than processes — creating and switching threads is faster."),
                LevelEnum.advanced: ("Advanced Process Management", "The fork-exec model in Unix: fork() creates an exact copy of the calling process. exec() replaces the process's memory space with a new program. This combination is how shells execute commands.\n\nZombie processes: A terminated process that hasn't been waited on by its parent. The PCB remains until the parent calls wait(). Orphan processes: Parent died before child. Inherited by init/systemd.\n\nLinux CFS (Completely Fair Scheduler) uses a red-black tree ordered by virtual runtime to ensure every process gets a fair share of CPU. Processes with less CPU time are prioritized. Provides O(log n) scheduling decisions.\n\nCgroups (control groups) limit, account for, and isolate resource usage of process groups. Foundation of containerization — Docker uses cgroups to enforce CPU and memory limits per container."),
            },
            "quiz": [
                {"text": "What is a process?", "option_a": "A stored program on disk", "option_b": "A program in execution", "option_c": "A hardware component", "option_d": "A network connection", "correct": "B", "explanation": "A process is a program in execution — it includes the code, current activity, and resources allocated by the OS."},
                {"text": "What does PCB stand for?", "option_a": "Program Control Base", "option_b": "Process Control Block", "option_c": "Processor Cache Buffer", "option_d": "Primary Code Block", "correct": "B", "explanation": "PCB (Process Control Block) stores all information about a process including its state, registers, and memory information."},
                {"text": "What is a context switch?", "option_a": "Changing the display settings", "option_b": "Switching between user and kernel mode", "option_c": "Saving current process state and loading next process state", "option_d": "Changing network connections", "correct": "C", "explanation": "A context switch saves the current process's state to its PCB and loads the next process's state, allowing the CPU to switch between processes."},
                {"text": "Which Unix system call creates a new process?", "option_a": "exec()", "option_b": "spawn()", "option_c": "create()", "option_d": "fork()", "correct": "D", "explanation": "fork() creates a new process by duplicating the calling process. The child is an exact copy of the parent."},
                {"text": "How do threads differ from processes?", "option_a": "Threads are slower", "option_b": "Threads have separate memory spaces", "option_c": "Threads share the same memory space", "option_d": "Threads cannot communicate", "correct": "C", "explanation": "Threads within the same process share memory and resources but have separate stacks and registers, making them lighter than processes."},
            ]
        },
        {
            "title": "CPU Scheduling",
            "content": {
                LevelEnum.foundational: ("Introduction to CPU Scheduling", "CPU scheduling determines which process in the ready queue gets the CPU next. Since only one process can run on a single CPU at a time, the scheduler must make efficient decisions to maximize CPU utilization and system throughput.\n\nScheduling criteria: CPU utilization (keep CPU busy), throughput (processes completed per unit time), turnaround time (time to complete a process), waiting time (time in ready queue), response time (time until first response).\n\nPreemptive scheduling: The OS can forcibly remove a running process from the CPU. Allows better responsiveness. Non-preemptive scheduling: A process runs until it voluntarily releases the CPU or terminates. Simpler but can cause starvation.\n\nThe scheduler runs very frequently — thousands of times per second. It must make decisions quickly while minimizing overhead."),
                LevelEnum.intermediate: ("Scheduling Algorithms", "First Come First Served (FCFS): Processes are served in arrival order. Simple but causes convoy effect — short processes wait behind long ones. Average waiting time can be very high.\n\nShortest Job First (SJF): Process with smallest CPU burst runs next. Optimal average waiting time but requires knowing future burst times. Can cause starvation of long processes.\n\nRound Robin (RR): Each process gets a small time quantum (10-100ms). After quantum expires, process is preempted and moved to end of queue. Fair, good for time-sharing systems. Performance depends on quantum size.\n\nPriority Scheduling: Each process has a priority. Higher priority processes run first. Starvation problem — low priority processes may never run. Solution: aging (gradually increase priority of waiting processes).\n\nMultilevel Queue: Multiple queues with different scheduling algorithms. Processes assigned to queues based on properties (interactive vs batch). Multilevel Feedback Queue allows processes to move between queues."),
                LevelEnum.advanced: ("Real-Time and Modern Scheduling", "Real-time scheduling must meet timing constraints. Rate Monotonic Scheduling assigns priorities based on periods — shorter period = higher priority. Earliest Deadline First (EDF) always runs the process with the nearest deadline. Optimal for preemptive uniprocessor systems.\n\nMultiprocessor scheduling: Load balancing distributes work across CPUs. Processor affinity keeps processes on the same CPU to exploit cache warmth. NUMA (Non-Uniform Memory Access) architectures require careful scheduling to minimize remote memory accesses.\n\nLinux O(1) scheduler (2.4-2.6 kernel): Maintained two arrays of 140 priority queues. Achieved O(1) scheduling but poor interactive performance.\n\nLinux CFS (2.6.23+): Uses virtual runtime to track how much CPU each process has received. Maintains a red-black tree sorted by virtual runtime. Always picks the leftmost (lowest virtual runtime) node — O(log n). Achieves fairness while maintaining good performance."),
            },
            "quiz": [
                {"text": "Which scheduling algorithm has the optimal average waiting time?", "option_a": "FCFS", "option_b": "Round Robin", "option_c": "SJF", "option_d": "Priority", "correct": "C", "explanation": "Shortest Job First (SJF) has the optimal average waiting time by always running the shortest available process next."},
                {"text": "What is the convoy effect in FCFS scheduling?", "option_a": "Processes running in parallel", "option_b": "Short processes waiting behind a long process", "option_c": "High priority processes blocking low priority ones", "option_d": "CPU staying idle unnecessarily", "correct": "B", "explanation": "The convoy effect occurs in FCFS when many short processes must wait for one long process to complete, reducing CPU utilization."},
                {"text": "Round Robin scheduling is most suitable for:", "option_a": "Batch processing", "option_b": "Real-time systems", "option_c": "Time-sharing systems", "option_d": "Single-user systems", "correct": "C", "explanation": "Round Robin is ideal for time-sharing systems because it gives each process a fair time quantum, providing good response times for interactive users."},
                {"text": "What problem does aging solve in priority scheduling?", "option_a": "Convoy effect", "option_b": "Starvation", "option_c": "Deadlock", "option_d": "Memory leaks", "correct": "B", "explanation": "Aging gradually increases the priority of processes that have been waiting a long time, preventing starvation of low-priority processes."},
                {"text": "Which Linux scheduler uses a red-black tree for O(log n) scheduling?", "option_a": "O(1) Scheduler", "option_b": "Round Robin", "option_c": "Completely Fair Scheduler (CFS)", "option_d": "EDF Scheduler", "correct": "C", "explanation": "CFS uses a red-black tree sorted by virtual runtime, always selecting the process with the least CPU time for O(log n) scheduling decisions."},
            ]
        },
        {
            "title": "Memory Management",
            "content": {
                LevelEnum.foundational: ("Introduction to Memory Management", "Memory management is one of the most critical OS functions. It tracks which parts of memory are in use, allocates memory to processes when needed, and reclaims it when processes finish.\n\nPhysical memory is the actual RAM chips. Virtual memory gives each process the illusion of having its own large, contiguous address space even if physical memory is fragmented or insufficient.\n\nThe OS maintains a memory map showing which regions are free or allocated. Memory allocation strategies: First Fit (allocate first large enough hole), Best Fit (allocate smallest sufficient hole), Worst Fit (allocate largest hole).\n\nFragmentation is a major problem: External fragmentation — free memory exists but is scattered in small pieces. Internal fragmentation — allocated memory is slightly larger than requested, wasting space inside blocks."),
                LevelEnum.intermediate: ("Paging and Virtual Memory", "Paging divides physical memory into fixed-size frames and virtual memory into same-sized pages. The OS maintains a page table mapping virtual pages to physical frames. This eliminates external fragmentation and allows non-contiguous allocation.\n\nThe Translation Lookaside Buffer (TLB) is a hardware cache of recent page table entries. With TLB, most address translations take 1-2 cycles instead of multiple memory accesses. TLB hit rate of 99%+ is typical.\n\nPage faults occur when a process accesses a page not in physical memory. The OS loads the page from disk (swap space), updates the page table, and resumes the process. The process doesn't know this happened — it's transparent.\n\nPage replacement algorithms decide which page to evict when memory is full: FIFO (evict oldest), LRU (evict least recently used — best in practice), Optimal (evict page used furthest in future — theoretical best)."),
                LevelEnum.advanced: ("Advanced Memory Management", "Segmentation divides memory by logical units (code segment, data segment, stack). Each segment has a base and limit. Allows sharing and protection at a logical level. Intel x86 originally used segmentation; modern OS mostly uses paging.\n\nDemand paging only loads pages when accessed, not at process startup. Reduces startup time and memory usage. Working set model: the set of pages a process needs at any time. Thrashing occurs when processes spend more time swapping than executing — caused by insufficient physical memory.\n\nMemory-mapped files map files directly into virtual address space. Reads and writes to the mapped region become file operations. Used for shared libraries (libc is memory-mapped into every process) and inter-process shared memory.\n\nHuge pages (Linux) and Large pages (Windows) use 2MB or 1GB pages instead of 4KB. Reduces TLB misses for memory-intensive applications. Databases like PostgreSQL and Oracle benefit greatly from huge pages."),
            },
            "quiz": [
                {"text": "What problem does paging solve?", "option_a": "Internal fragmentation", "option_b": "External fragmentation", "option_c": "Process starvation", "option_d": "Deadlock", "correct": "B", "explanation": "Paging eliminates external fragmentation by dividing memory into fixed-size frames, allowing non-contiguous physical allocation."},
                {"text": "What is the TLB?", "option_a": "A type of RAM", "option_b": "A cache of recent page table entries", "option_c": "A disk buffer", "option_d": "A CPU register", "correct": "B", "explanation": "The TLB (Translation Lookaside Buffer) is a hardware cache of recent page table entries that speeds up virtual-to-physical address translation."},
                {"text": "What causes a page fault?", "option_a": "A hardware error", "option_b": "A program crash", "option_c": "Accessing a page not in physical memory", "option_d": "Memory overflow", "correct": "C", "explanation": "A page fault occurs when a process accesses a page that is not currently in physical memory, causing the OS to load it from disk."},
                {"text": "Which page replacement algorithm is theoretically optimal?", "option_a": "FIFO", "option_b": "LRU", "option_c": "Clock", "option_d": "Optimal (OPT)", "correct": "D", "explanation": "The Optimal algorithm evicts the page that will be used furthest in the future, minimizing page faults. It is theoretical since it requires future knowledge."},
                {"text": "What is thrashing?", "option_a": "CPU overheating", "option_b": "Excessive context switching", "option_c": "Processes spending more time swapping than executing", "option_d": "Memory corruption", "correct": "C", "explanation": "Thrashing occurs when insufficient physical memory causes continuous page swapping, drastically reducing system performance."},
            ]
        },
        {
            "title": "File Systems",
            "content": {
                LevelEnum.foundational: ("Introduction to File Systems", "A file system organizes and stores data on storage devices. It provides an abstraction over raw storage, presenting data as named files organized in directories.\n\nA file is a named collection of related data. Files have attributes: name, type, size, location, timestamps (created, modified, accessed), permissions, and owner.\n\nDirectory structures organize files hierarchically. A path uniquely identifies a file: absolute path starts from root (/home/user/file.txt), relative path from current directory (./file.txt or ../other/file.txt).\n\nFile operations: create, read, write, seek, delete, truncate. The OS maintains an open file table tracking which files are open, their current position, and access mode. File descriptors (Unix) or handles (Windows) reference open files."),
                LevelEnum.intermediate: ("File System Implementation", "File system structures: Boot block (boot code), Superblock (file system metadata — size, free blocks, inode count), Inode table (file metadata), Data blocks (actual file content).\n\nInodes (index nodes) store file metadata: permissions, owner, timestamps, size, and pointers to data blocks. Inodes do NOT store the filename — that's stored in the directory. Direct pointers, indirect pointers, double indirect, and triple indirect pointers allow files up to several terabytes.\n\nDirectory implementation: Linear list (simple, slow search), Hash table (faster search, handles collisions), B-tree (used in modern file systems like HFS+, NTFS for large directories).\n\nFree space management: Bit vector (one bit per block), Linked list (free blocks linked together), Grouping (addresses of free blocks stored in blocks). Most modern file systems use bitmaps."),
                LevelEnum.advanced: ("Modern File Systems and Journaling", "Journaling file systems prevent corruption by logging changes before applying them. If a crash occurs mid-operation, the journal is replayed on recovery. Ext4, NTFS, XFS, and ZFS all use journaling.\n\nJournal modes: Writeback (only metadata journaled — fastest, least safe), Ordered (data written before metadata — default in ext4), Data journaling (both data and metadata — slowest, safest).\n\nZFS (Zettabyte File System) combines file system and volume management. Features: checksums on all data (detects corruption), Copy-on-Write (never overwrites data in place), snapshots (instant, space-efficient), RAID-Z (software RAID with better reliability than hardware RAID).\n\nSSDs require different optimization than HDDs. SSDs cannot overwrite in place — must erase entire blocks before writing. TRIM command tells SSD which blocks are free. Wear leveling distributes writes to avoid burning out specific cells. Flash-friendly file systems (F2FS) optimize for SSD characteristics."),
            },
            "quiz": [
                {"text": "What does an inode store?", "option_a": "The filename", "option_b": "File metadata and pointers to data blocks", "option_c": "The directory structure", "option_d": "The file system type", "correct": "B", "explanation": "Inodes store file metadata (permissions, timestamps, size) and pointers to data blocks. The filename is stored in the directory, not the inode."},
                {"text": "What is the purpose of journaling in file systems?", "option_a": "To improve read speeds", "option_b": "To compress files", "option_c": "To prevent corruption by logging changes before applying them", "option_d": "To encrypt files", "correct": "C", "explanation": "Journaling logs file system changes before applying them, allowing recovery to a consistent state if a crash occurs mid-operation."},
                {"text": "What is the superblock?", "option_a": "The first file in the system", "option_b": "File system metadata including size and free block count", "option_c": "The root directory", "option_d": "A type of inode", "correct": "B", "explanation": "The superblock stores critical file system metadata: total size, free blocks, inode count, and other administrative information."},
                {"text": "Which file system feature provides instant space-efficient snapshots?", "option_a": "Journaling", "option_b": "RAID", "option_c": "Copy-on-Write (ZFS)", "option_d": "Defragmentation", "correct": "C", "explanation": "ZFS uses Copy-on-Write which never overwrites data in place, making instant snapshots possible with no immediate space overhead."},
                {"text": "Why do SSDs require TRIM?", "option_a": "To speed up reads", "option_b": "To reduce power consumption", "option_c": "Because SSDs cannot overwrite in place and need to know which blocks are free", "option_d": "To encrypt data", "correct": "C", "explanation": "SSDs must erase entire blocks before writing. TRIM tells the SSD which blocks are no longer needed so it can erase them proactively, maintaining write performance."},
            ]
        },
        {
            "title": "Concurrency",
            "content": {
                LevelEnum.foundational: ("Introduction to Concurrency", "Concurrency means multiple computations happening at the same time. In an OS, multiple processes or threads execute concurrently, sharing resources like memory, files, and devices.\n\nA race condition occurs when multiple threads access shared data concurrently and the result depends on the order of access. This leads to unpredictable, hard-to-reproduce bugs.\n\nExample: Two threads both read a counter (value=5), both add 1, both write back 6. The correct result should be 7. This is a race condition — the increment operation is not atomic.\n\nCritical section: A code segment that accesses shared resources and must not be executed by more than one thread at a time. Mutual exclusion ensures only one thread is in the critical section at a time."),
                LevelEnum.intermediate: ("Synchronization Mechanisms", "Mutex (Mutual Exclusion Lock): A thread acquires the mutex before entering the critical section and releases it when done. Other threads block until the mutex is available. Simple and effective for short critical sections.\n\nSemaphore: A counter with two atomic operations: wait() (decrement, block if 0) and signal() (increment, wake a blocked thread). Binary semaphore = mutex. Counting semaphore manages a pool of resources.\n\nMonitor: A high-level synchronization construct combining mutual exclusion with condition variables. Used in Java (synchronized methods), Python (threading.Condition). Easier to use correctly than semaphores.\n\nCondition Variables: Allow threads to wait for a specific condition while releasing the mutex. wait() atomically releases mutex and blocks. signal() wakes one waiting thread. broadcast() wakes all waiting threads."),
                LevelEnum.advanced: ("Advanced Concurrency and Lock-Free Programming", "Spinlocks: Thread busy-waits in a loop checking if the lock is available. Wastes CPU but avoids context switch overhead. Good for very short critical sections on multiprocessor systems. Linux kernel uses spinlocks extensively.\n\nRead-Write Locks: Allow multiple concurrent readers OR one exclusive writer. Improves performance for read-heavy workloads. Readers don't block each other. Writer must wait for all readers to finish.\n\nLock-free data structures use atomic compare-and-swap (CAS) operations instead of locks. CAS atomically: if memory[addr] == expected, memory[addr] = new_value. Lock-free stacks, queues, and hash maps eliminate lock contention in highly concurrent systems.\n\nMemory ordering and memory barriers: Modern CPUs reorder instructions for performance. Memory barriers (fences) ensure ordering constraints. C++ memory_order, Java volatile, and Go sync/atomic provide programmer control over memory ordering."),
            },
            "quiz": [
                {"text": "What is a race condition?", "option_a": "Two processes competing for CPU", "option_b": "Result depends on timing of concurrent accesses to shared data", "option_c": "A deadlock situation", "option_d": "CPU running at maximum speed", "correct": "B", "explanation": "A race condition occurs when the result of an operation depends on the relative timing of concurrent threads accessing shared data."},
                {"text": "What does mutual exclusion ensure?", "option_a": "Processes run in parallel", "option_b": "Only one thread executes in the critical section at a time", "option_c": "All threads finish at the same time", "option_d": "Threads never block", "correct": "B", "explanation": "Mutual exclusion ensures that only one thread can execute in the critical section at any given time, preventing race conditions."},
                {"text": "What is the difference between a binary semaphore and a mutex?", "option_a": "No difference", "option_b": "Mutex can only be released by the thread that acquired it", "option_c": "Semaphore is faster", "option_d": "Mutex allows multiple threads", "correct": "B", "explanation": "A mutex has ownership — only the thread that locked it can unlock it. A binary semaphore can be signaled by any thread, making it useful for signaling between threads."},
                {"text": "What does a condition variable's wait() operation do?", "option_a": "Acquires the mutex", "option_b": "Atomically releases the mutex and blocks the thread", "option_c": "Signals another thread", "option_d": "Spins waiting for a condition", "correct": "B", "explanation": "wait() atomically releases the associated mutex and blocks the calling thread, preventing deadlock while waiting for a condition to become true."},
                {"text": "What is a spinlock best suited for?", "option_a": "Long critical sections", "option_b": "Single-processor systems", "option_c": "Very short critical sections on multiprocessor systems", "option_d": "I/O operations", "correct": "C", "explanation": "Spinlocks busy-wait (waste CPU) but avoid context switch overhead. They are efficient only for very short critical sections on multiprocessor systems."},
            ]
        },
        {
            "title": "Deadlock",
            "content": {
                LevelEnum.foundational: ("What is Deadlock?", "Deadlock is a situation where two or more processes are waiting indefinitely for resources held by each other, resulting in none of them being able to proceed.\n\nClassic example: Process A holds resource 1 and waits for resource 2. Process B holds resource 2 and waits for resource 1. Both wait forever — deadlock.\n\nFour necessary conditions (Coffman conditions) — ALL must hold for deadlock: Mutual Exclusion (resources are non-shareable), Hold and Wait (process holds resources while waiting for more), No Preemption (resources cannot be forcibly taken), Circular Wait (circular chain of processes waiting for each other).\n\nDeadlocks can occur in operating systems, databases (transaction locks), networking, and any concurrent system where resources are held while waiting for others."),
                LevelEnum.intermediate: ("Deadlock Handling Strategies", "Deadlock Prevention: Eliminate one of the four conditions. Eliminate Hold-and-Wait: require processes to request all resources at once. Eliminate Circular Wait: impose a total ordering on resource types, always request in order.\n\nDeadlock Avoidance: Use algorithms that dynamically check if granting a request would lead to deadlock. Banker's Algorithm: maintains safe state by only granting requests that keep system in a safe state (there exists a sequence to complete all processes). Requires knowing maximum resource needs in advance.\n\nDeadlock Detection: Allow deadlocks to occur, then detect and recover. Maintain a resource allocation graph. A cycle indicates deadlock. Recovery: terminate processes (one at a time or all at once) or preempt resources (rollback transactions).\n\nDeadlock Ignorance (Ostrich Algorithm): Simply ignore the problem. Used in most modern OS (Windows, Linux) because deadlocks are rare and the overhead of prevention/avoidance is high."),
                LevelEnum.advanced: ("Deadlock in Distributed Systems", "Distributed deadlocks occur across multiple machines, making detection much harder. No single machine has complete system state.\n\nCentralized detection: One coordinator collects resource information and runs detection. Single point of failure and bottleneck.\n\nDistributed detection algorithms: Chandy-Misra-Haas algorithm uses probe messages. When a process waits for another, it sends a probe. If the probe returns to the sender, a deadlock is detected.\n\nDatabase deadlocks: Databases use lock managers with timeout-based detection or wait-for graph analysis. PostgreSQL detects deadlocks using a wait-for graph and terminates one transaction. Deadlock rates increase with transaction complexity and concurrency level.\n\nLock ordering in practice: The standard solution in kernel development and concurrent programming is to always acquire locks in the same global order. Linux kernel lock validator (lockdep) tracks lock acquisition order at runtime and warns about potential deadlocks."),
            },
            "quiz": [
                {"text": "Which of the following is NOT a necessary condition for deadlock?", "option_a": "Mutual Exclusion", "option_b": "Hold and Wait", "option_c": "Preemption", "option_d": "Circular Wait", "correct": "C", "explanation": "No Preemption (inability to forcibly take resources) is a necessary condition. Preemption (being ABLE to take resources) would break this condition and prevent deadlock."},
                {"text": "The Banker's Algorithm is used for:", "option_a": "Deadlock detection", "option_b": "Deadlock prevention", "option_c": "Deadlock avoidance", "option_d": "Deadlock recovery", "correct": "C", "explanation": "The Banker's Algorithm is a deadlock avoidance algorithm that ensures the system stays in a safe state by only granting resource requests that maintain safety."},
                {"text": "What is a safe state in deadlock avoidance?", "option_a": "No processes are running", "option_b": "There exists a sequence to complete all processes successfully", "option_c": "All resources are free", "option_d": "No circular waits exist", "correct": "B", "explanation": "A safe state means there exists at least one sequence in which all processes can complete using available resources without deadlock."},
                {"text": "Which deadlock strategy do most modern operating systems use?", "option_a": "Prevention", "option_b": "Avoidance", "option_c": "Detection and Recovery", "option_d": "Ignorance (Ostrich Algorithm)", "correct": "D", "explanation": "Most modern OS ignore deadlocks because they are rare for most applications and prevention/avoidance overhead is too high."},
                {"text": "Deadlock prevention by eliminating Circular Wait requires:", "option_a": "Requesting all resources at once", "option_b": "Imposing a total ordering on resource types", "option_c": "Allowing resource preemption", "option_d": "Sharing all resources", "correct": "B", "explanation": "Eliminating circular wait requires a total ordering of resource types and requiring all processes to request resources in that order, preventing cycles."},
            ]
        },
        {
            "title": "I/O Management",
            "content": {
                LevelEnum.foundational: ("Introduction to I/O Management", "I/O (Input/Output) management handles communication between the CPU/memory and peripheral devices like disks, keyboards, displays, and network interfaces.\n\nI/O devices vary enormously in speed, data transfer unit, and error conditions. The OS provides a uniform interface hiding device differences from applications.\n\nI/O methods: Programmed I/O (CPU polls device repeatedly — wastes CPU), Interrupt-driven I/O (device interrupts CPU when ready — more efficient), DMA Direct Memory Access (device transfers data directly to/from memory without CPU involvement — best for large transfers).\n\nDevice drivers are software modules that control specific hardware devices. They translate high-level OS requests into device-specific commands. Each device type has its own driver (disk driver, network driver, display driver)."),
                LevelEnum.intermediate: ("I/O Scheduling and Buffering", "Disk I/O scheduling orders requests to minimize seek time (moving disk arm). FCFS: simple but poor performance. SSTF (Shortest Seek Time First): serves nearest request next, reduces seek time but can cause starvation. SCAN (Elevator): arm moves back and forth serving requests — fair and efficient. C-SCAN: arm moves in one direction only, then jumps back — more uniform wait times.\n\nBuffering stores data temporarily during transfer. Single buffer: CPU processes while device fills next buffer. Double buffer: two buffers alternate — CPU always has data to process. Circular buffer: multiple buffers in a ring, used for streaming.\n\nCaching stores frequently accessed data in memory. Read cache reduces disk reads. Write cache (write buffer) accumulates writes and flushes periodically. Write-through cache writes to disk immediately — safer but slower. Write-back cache writes to disk lazily — faster but risks data loss on crash.\n\nSpooling (Simultaneous Peripheral Operations On-Line): stores output for slow devices in fast storage. Print spooling sends jobs to a queue on disk, allowing multiple applications to print concurrently."),
                LevelEnum.advanced: ("Advanced I/O and Storage Systems", "NVMe (Non-Volatile Memory Express): Protocol designed specifically for SSDs. Uses PCIe interface with up to 64K queues of 64K commands each (vs SATA's single queue of 32). Delivers latency <100 microseconds and throughput >7 GB/s.\n\nStorage Area Networks (SAN) and Network Attached Storage (NAS): SAN presents storage as block devices over a network (iSCSI, Fibre Channel). NAS presents storage as file systems over a network (NFS, SMB). Used in enterprise data centers for centralized, shared storage.\n\nRAID (Redundant Array of Independent Disks): RAID 0 (striping) — performance, no redundancy. RAID 1 (mirroring) — full redundancy, 50% capacity. RAID 5 (striping with parity) — balance of performance and redundancy, survives one disk failure. RAID 6 — survives two disk failures.\n\nio_uring (Linux 5.1+): New asynchronous I/O interface using two ring buffers shared between kernel and userspace. Eliminates system call overhead for high-performance I/O. Used by databases, web servers, and storage systems for maximum I/O throughput."),
            },
            "quiz": [
                {"text": "Which I/O method wastes CPU by repeatedly checking device status?", "option_a": "Interrupt-driven I/O", "option_b": "DMA", "option_c": "Programmed I/O", "option_d": "Buffered I/O", "correct": "C", "explanation": "Programmed I/O has the CPU continuously poll the device status (busy waiting), wasting CPU cycles that could be used for other work."},
                {"text": "What does DMA stand for and what is its benefit?", "option_a": "Direct Memory Access — transfers data without CPU involvement", "option_b": "Dynamic Memory Allocation — allocates memory dynamically", "option_c": "Disk Management Algorithm — optimizes disk access", "option_d": "Data Management API — provides I/O interface", "correct": "A", "explanation": "DMA (Direct Memory Access) allows devices to transfer data directly to/from memory without CPU involvement, freeing the CPU for other work."},
                {"text": "Which disk scheduling algorithm is called the elevator algorithm?", "option_a": "FCFS", "option_b": "SSTF", "option_c": "SCAN", "option_d": "C-SCAN", "correct": "C", "explanation": "SCAN (elevator algorithm) moves the disk arm back and forth, servicing requests in both directions like an elevator, providing good performance and fairness."},
                {"text": "What is write-back caching?", "option_a": "Writing to disk immediately", "option_b": "Writing to cache and disk simultaneously", "option_c": "Writing to cache first and flushing to disk lazily", "option_d": "Reading from disk and caching the result", "correct": "C", "explanation": "Write-back caching writes data to cache immediately and flushes to disk later, improving write performance but risking data loss on sudden power failure."},
                {"text": "Which RAID level provides striping with parity and survives one disk failure?", "option_a": "RAID 0", "option_b": "RAID 1", "option_c": "RAID 5", "option_d": "RAID 10", "correct": "C", "explanation": "RAID 5 stripes data with distributed parity across all disks, providing good performance and capacity while tolerating one disk failure."},
            ]
        },
        {
            "title": "Virtualization",
            "content": {
                LevelEnum.foundational: ("Introduction to Virtualization", "Virtualization creates a virtual version of something — hardware, OS, storage, or network. It allows multiple virtual machines to run on one physical machine, improving resource utilization and flexibility.\n\nA hypervisor (Virtual Machine Monitor) is the software layer that creates and manages virtual machines. It allocates physical resources to VMs and ensures isolation between them.\n\nType 1 (Bare Metal) hypervisors run directly on hardware: VMware ESXi, Microsoft Hyper-V, Xen. Used in enterprise data centers. Better performance and security.\n\nType 2 (Hosted) hypervisors run on top of a host OS: VirtualBox, VMware Workstation, Parallels. Used for development and testing. Easier to install and use but higher overhead.\n\nVirtual machines have their own virtual CPU, memory, storage, and network interfaces. From the guest OS's perspective, it appears to run on real hardware."),
                LevelEnum.intermediate: ("Virtualization Techniques and Containers", "Full virtualization: Guest OS runs unmodified. Hypervisor intercepts and emulates all privileged instructions. Performance overhead from emulation. Intel VT-x and AMD-V provide hardware-assisted virtualization — dramatically reduces overhead.\n\nPara-virtualization: Guest OS is modified to use hypercalls instead of privileged instructions. Xen's approach. Better performance than full virtualization but requires modifying guest OS.\n\nContainerization (OS-level virtualization): Containers share the host kernel but have isolated user spaces. Docker, podman, containerd. Much lighter than VMs — millisecond startup, megabyte overhead. Linux namespaces provide isolation (PID, network, filesystem, IPC). Cgroups enforce resource limits.\n\nDocker architecture: Dockerfile defines image layers. Images are read-only layers built on base images. Containers add a writable layer on top. Layer caching makes builds fast. Docker Hub stores and shares images."),
                LevelEnum.advanced: ("Cloud Virtualization and Kubernetes", "Cloud computing is built on virtualization. IaaS (Infrastructure as a Service) provides virtual machines (AWS EC2, Azure VMs). PaaS provides platforms (Google App Engine, Heroku). SaaS provides applications (Gmail, Office 365).\n\nLive migration moves running VMs between physical hosts with minimal downtime. Pre-copy migration: copy memory pages while VM runs, then briefly pause to copy remaining dirty pages. Used for maintenance and load balancing in data centers.\n\nKubernetes orchestrates containerized applications at scale. Key concepts: Pod (smallest unit — one or more containers), Service (stable endpoint for pods), Deployment (manages pod replicas), Namespace (isolation boundary). kubectl is the command-line interface.\n\nServerless computing (AWS Lambda, Google Cloud Functions) abstracts away all infrastructure. Code runs in response to events. Platform manages scaling, OS, runtime. Priced per execution. Cold starts (first invocation latency) are a challenge — mitigated by provisioned concurrency."),
            },
            "quiz": [
                {"text": "What is a Type 1 hypervisor?", "option_a": "Runs on top of a host operating system", "option_b": "Runs directly on bare hardware", "option_c": "A containerization platform", "option_d": "A software emulator", "correct": "B", "explanation": "Type 1 (bare metal) hypervisors run directly on physical hardware without a host OS, providing better performance and security. Examples: VMware ESXi, Xen."},
                {"text": "How do containers differ from virtual machines?", "option_a": "Containers are slower", "option_b": "Containers have their own kernel", "option_c": "Containers share the host kernel but have isolated user spaces", "option_d": "Containers require more memory", "correct": "C", "explanation": "Containers share the host OS kernel using Linux namespaces and cgroups for isolation, making them much lighter and faster than VMs which include a full OS."},
                {"text": "What Linux feature do containers use to enforce resource limits?", "option_a": "Namespaces", "option_b": "Cgroups", "option_c": "Systemd", "option_d": "Iptables", "correct": "B", "explanation": "Cgroups (control groups) enforce CPU, memory, and I/O limits per container. Namespaces provide isolation of process IDs, network, and filesystem."},
                {"text": "What is the smallest deployable unit in Kubernetes?", "option_a": "Container", "option_b": "Service", "option_c": "Node", "option_d": "Pod", "correct": "D", "explanation": "A Pod is the smallest deployable unit in Kubernetes. It can contain one or more tightly coupled containers that share network and storage."},
                {"text": "What is live migration in virtualization?", "option_a": "Moving files between VMs", "option_b": "Moving a running VM to another host with minimal downtime", "option_c": "Upgrading a VM's operating system", "option_d": "Scaling a VM horizontally", "correct": "B", "explanation": "Live migration moves a running VM from one physical host to another with minimal downtime, used for maintenance, load balancing, and power management."},
            ]
        },
    ]

    # ── SE modules content ─────────────────────────────
    se_modules_data = [
        {
            "title": "SDLC Models",
            "content": {
                LevelEnum.foundational: ("What is SDLC?", "The Software Development Life Cycle (SDLC) is a structured process for planning, creating, testing, and deploying software. It provides a framework that defines activities and deliverables at each stage of development.\n\nThe main phases of SDLC: Planning (define scope, feasibility, resources), Requirements Analysis (gather and document what the system should do), System Design (architect the solution), Implementation (write the code), Testing (verify the software works correctly), Deployment (release to users), Maintenance (fix bugs, add features).\n\nDifferent SDLC models structure these phases differently: Waterfall (sequential), Agile (iterative), Spiral (risk-driven), V-Model (verification and validation focused).\n\nChoosing the right SDLC model depends on project size, requirements stability, team experience, client involvement, and risk tolerance."),
                LevelEnum.intermediate: ("Waterfall, Agile, and Spiral Models", "Waterfall Model: Sequential phases, each completed before the next begins. Requirements → Design → Implementation → Testing → Deployment → Maintenance. Advantages: Simple, well-documented, clear milestones. Disadvantages: Inflexible to change, customer sees product only at the end, late defect detection.\n\nAgile Model: Iterative development in short sprints (1-4 weeks). Each sprint delivers working software. Customer involved throughout. Adapts to changing requirements. Scrum and Kanban are popular Agile frameworks. Advantages: Flexible, early delivery, continuous feedback. Disadvantages: Difficult to predict total cost and timeline.\n\nSpiral Model: Risk-driven process combining Waterfall and prototyping. Each spiral cycle: Plan → Risk Analysis → Engineer → Evaluate. Good for large, complex, high-risk projects. Disadvantages: Expensive, complex risk assessment required.\n\nV-Model: Extension of Waterfall with corresponding testing phase for each development phase. Requirements → System Design → Architecture Design → Module Design → Implementation, with verification and validation at each level. Emphasizes testing throughout."),
                LevelEnum.advanced: ("Modern Development Practices", "DevOps bridges development and operations. Continuous Integration (CI) automatically builds and tests code on every commit. Continuous Deployment (CD) automatically deploys to production after tests pass. CI/CD pipelines (GitHub Actions, Jenkins, GitLab CI) automate the entire software delivery process.\n\nSite Reliability Engineering (SRE): Google's approach to operations. SREs are software engineers managing production systems. Error budgets define acceptable downtime. SLOs (Service Level Objectives) define reliability targets. Toil reduction through automation.\n\nMicroservices architecture: Application split into small, independent services each running its own process. Services communicate via APIs. Each can be deployed, scaled, and updated independently. Challenges: distributed system complexity, network latency, data consistency.\n\nInfrastructure as Code (IaC): Infrastructure defined in code (Terraform, Ansible, CloudFormation). Version controlled, reproducible, automated. Eliminates configuration drift and manual errors. Enables spinning up identical environments in minutes."),
            },
            "quiz": [
                {"text": "Which SDLC model requires all requirements to be complete before development begins?", "option_a": "Agile", "option_b": "Spiral", "option_c": "Waterfall", "option_d": "Scrum", "correct": "C", "explanation": "The Waterfall model is sequential — each phase must be completed before the next begins, requiring complete requirements before development starts."},
                {"text": "What is the main advantage of Agile over Waterfall?", "option_a": "Better documentation", "option_b": "Lower cost", "option_c": "Flexibility to accommodate changing requirements", "option_d": "Simpler project management", "correct": "C", "explanation": "Agile's iterative approach allows requirements to evolve throughout the project, making it much more flexible than Waterfall's rigid sequential process."},
                {"text": "What drives the Spiral model?", "option_a": "Cost reduction", "option_b": "Risk analysis", "option_c": "Customer requirements", "option_d": "Team size", "correct": "B", "explanation": "The Spiral model is risk-driven — each cycle includes risk analysis and mitigation, making it suitable for large, complex, high-risk projects."},
                {"text": "What does CI/CD stand for in modern software development?", "option_a": "Code Integration/Code Deployment", "option_b": "Continuous Integration/Continuous Deployment", "option_c": "Client Interface/Client Design", "option_d": "Component Integration/Component Deployment", "correct": "B", "explanation": "CI/CD stands for Continuous Integration (automatically building and testing on each commit) and Continuous Deployment (automatically deploying after tests pass)."},
                {"text": "What is the V-Model's key characteristic?", "option_a": "Iterative development", "option_b": "Risk-driven planning", "option_c": "Corresponding testing phase for each development phase", "option_d": "Unlimited requirement changes", "correct": "C", "explanation": "The V-Model pairs each development phase with a corresponding testing/validation phase, emphasizing verification and validation throughout development."},
            ]
        },
        {
            "title": "Requirements Analysis",
            "content": {
                LevelEnum.foundational: ("What are Requirements?", "Requirements define what a software system should do and the constraints under which it operates. Good requirements are the foundation of successful software — poor requirements are the most common cause of project failure.\n\nFunctional requirements describe what the system should do: features, behaviors, and functions. Example: 'The system shall allow users to register with email and password.'\n\nNon-functional requirements describe how the system should perform: performance, security, usability, reliability, scalability. Example: 'The system shall respond to login requests within 200 milliseconds.'\n\nStakeholders are everyone with an interest in the system: end users, customers, managers, developers, regulators. Requirements must capture all stakeholder needs, not just what the paying customer asks for."),
                LevelEnum.intermediate: ("Requirements Elicitation and Documentation", "Requirements elicitation techniques: Interviews (one-on-one with stakeholders), Surveys/Questionnaires (large groups), Workshops (collaborative group sessions), Observation (watch users in their environment), Prototyping (build mockups to clarify requirements), Document Analysis (study existing systems).\n\nUse cases describe system interactions from the user's perspective. A use case has: Actor (who interacts with system), Goal (what actor wants to achieve), Preconditions, Main success scenario, Alternative flows, Postconditions.\n\nUser Stories (Agile): Short descriptions from user's perspective. Format: 'As a [user type], I want [goal] so that [benefit].' Example: 'As a student, I want to receive immediate quiz feedback so that I can understand my mistakes.'\n\nRequirements specification document (SRS - Software Requirements Specification): Formal document describing all system requirements. Includes scope, assumptions, functional requirements, non-functional requirements, constraints, and glossary."),
                LevelEnum.advanced: ("Requirements Management and Traceability", "Requirements traceability tracks relationships between requirements and other artifacts (design documents, code, tests). Forward traceability: requirement → design → code → test. Backward traceability: test → code → design → requirement. Critical for change impact analysis and compliance.\n\nRequirements prioritization: MoSCoW method categorizes requirements as Must Have, Should Have, Could Have, Won't Have. Helps focus development on highest-value features first.\n\nRequirements verification vs validation: Verification asks 'Are we building the product right?' (does it match the specification). Validation asks 'Are we building the right product?' (does it meet user needs). Both are necessary.\n\nFormal methods use mathematical notation to specify requirements precisely, eliminating ambiguity. Z notation, B method, Alloy. Used in safety-critical systems (aviation, medical, nuclear). High precision but require specialized expertise."),
            },
            "quiz": [
                {"text": "What is the difference between functional and non-functional requirements?", "option_a": "Functional requirements are more important", "option_b": "Functional requirements describe what the system does; non-functional describe how well it does it", "option_c": "Non-functional requirements are optional", "option_d": "Functional requirements describe hardware needs", "correct": "B", "explanation": "Functional requirements define features and behaviors (what the system does). Non-functional requirements define quality attributes like performance, security, and usability (how well it does it)."},
                {"text": "What format do Agile user stories follow?", "option_a": "If [condition] then [action]", "option_b": "The system shall [action]", "option_c": "As a [user], I want [goal] so that [benefit]", "option_d": "Given [context] when [action] then [outcome]", "correct": "C", "explanation": "Agile user stories follow the format: 'As a [user type], I want [goal] so that [benefit]', capturing who wants what and why."},
                {"text": "What does SRS stand for?", "option_a": "System Reliability Standard", "option_b": "Software Requirements Specification", "option_c": "Software Release Schedule", "option_d": "System Resource Summary", "correct": "B", "explanation": "SRS stands for Software Requirements Specification — the formal document that describes all functional and non-functional requirements for a system."},
                {"text": "What does the MoSCoW method help with?", "option_a": "Code documentation", "option_b": "Testing strategies", "option_c": "Requirements prioritization", "option_d": "Team organization", "correct": "C", "explanation": "MoSCoW (Must Have, Should Have, Could Have, Won't Have) is a requirements prioritization technique that helps teams focus on the most valuable features first."},
                {"text": "What is requirements traceability?", "option_a": "Tracking bugs in requirements", "option_b": "Tracking relationships between requirements and design, code, and tests", "option_c": "Documenting requirement changes", "option_d": "Monitoring project progress", "correct": "B", "explanation": "Requirements traceability tracks relationships between requirements and other artifacts (design, code, tests) to support change impact analysis and compliance."},
            ]
        },
        {
            "title": "UML Design",
            "content": {
                LevelEnum.foundational: ("Introduction to UML", "UML (Unified Modeling Language) is a standardized visual language for modeling software systems. It provides diagrams to describe structure, behavior, and interactions at different levels of abstraction.\n\nUML has two main categories of diagrams: Structural diagrams (show static structure) include Class, Object, Component, and Deployment diagrams. Behavioral diagrams (show dynamic behavior) include Use Case, Sequence, Activity, and State Machine diagrams.\n\nUML is not a programming language — it is a design notation. You use UML to plan and communicate your design before and during implementation.\n\nUML diagrams help teams: Communicate design ideas visually, detect design problems early, document the system for maintenance, onboard new team members quickly."),
                LevelEnum.intermediate: ("Key UML Diagrams", "Class Diagram (most important): Shows classes, attributes, methods, and relationships. Relationships: Association (uses), Aggregation (has-a, can exist independently), Composition (has-a, cannot exist independently), Inheritance (is-a), Dependency (uses temporarily), Realization (implements interface).\n\nSequence Diagram: Shows how objects interact over time. Vertical axis is time. Horizontal axis shows objects. Arrows represent messages. Activation boxes show when objects are active. Used to model use case flows.\n\nUse Case Diagram: Shows system functionality from user perspective. Actors (users/systems) interact with use cases (features). Include relationship (one use case uses another). Extend relationship (optional extension). Used for requirements documentation.\n\nActivity Diagram: Flowchart for business processes or algorithms. Shows flow of control, parallel activities, decision points, start and end nodes. Similar to flowcharts but supports concurrent flows with fork and join nodes."),
                LevelEnum.advanced: ("Advanced UML and Design Patterns", "State Machine Diagram: Models object lifecycle — states, transitions, events, and actions. Each state represents a stable situation. Transitions are triggered by events and may have guard conditions. Essential for modeling reactive systems, protocols, and UI workflows.\n\nComponent Diagram: Shows high-level components and their interfaces. Components provide and require interfaces. Used for system architecture documentation and component-based development.\n\nDesign patterns are reusable solutions to common design problems. Creational: Singleton (one instance), Factory Method (defer instantiation), Builder (complex object construction). Structural: Adapter (interface conversion), Decorator (add behavior), Facade (simplified interface). Behavioral: Observer (event notification), Strategy (interchangeable algorithms), Command (encapsulate requests).\n\nUML in Agile: Lightweight UML usage — sketch diagrams as needed, don't maintain them as separate artifacts. Use whiteboards and photos. Focus on communicating design, not producing comprehensive documentation."),
            },
            "quiz": [
                {"text": "What does UML stand for?", "option_a": "Universal Modeling Language", "option_b": "Unified Modeling Language", "option_c": "Unified Module Language", "option_d": "Universal Module Logic", "correct": "B", "explanation": "UML stands for Unified Modeling Language — a standardized notation for modeling software systems visually."},
                {"text": "Which UML diagram shows classes and their relationships?", "option_a": "Sequence Diagram", "option_b": "Use Case Diagram", "option_c": "Class Diagram", "option_d": "Activity Diagram", "correct": "C", "explanation": "Class diagrams show classes, their attributes and methods, and the relationships between classes (inheritance, association, composition, etc.)."},
                {"text": "What does a Sequence Diagram show?", "option_a": "System architecture", "option_b": "Object interactions over time", "option_c": "User requirements", "option_d": "Database schema", "correct": "B", "explanation": "Sequence diagrams show how objects interact with each other over time, depicting the sequence of messages exchanged between objects."},
                {"text": "The Observer design pattern is used for:", "option_a": "Creating objects without specifying class", "option_b": "Converting interfaces", "option_c": "Event notification — objects subscribe to changes in another object", "option_d": "Simplifying complex interfaces", "correct": "C", "explanation": "The Observer pattern defines a one-to-many dependency where multiple observers are notified when a subject changes state. Used extensively in event systems and MVC."},
                {"text": "What is Composition in UML class diagrams?", "option_a": "A class using another class temporarily", "option_b": "A child class inheriting from parent", "option_c": "A strong has-a relationship where the part cannot exist without the whole", "option_d": "A class implementing an interface", "correct": "C", "explanation": "Composition is a strong has-a relationship where the contained object cannot exist independently of the container. If the container is destroyed, so are its parts."},
            ]
        },
        {
            "title": "Testing Strategies",
            "content": {
                LevelEnum.foundational: ("Introduction to Software Testing", "Software testing verifies that software meets requirements and identifies defects before they reach users. Testing cannot prove software is bug-free, but it significantly increases confidence.\n\nVerification asks 'Are we building the product right?' — checking against specifications. Validation asks 'Are we building the right product?' — checking against user needs.\n\nTest levels: Unit testing (individual functions/methods), Integration testing (components working together), System testing (complete system), Acceptance testing (user confirms requirements met).\n\nBlack box testing: Tester has no knowledge of internal code. Tests based on inputs and expected outputs. White box testing: Tester knows the internal code. Designs tests to cover specific code paths. Grey box testing: Partial knowledge of internals."),
                LevelEnum.intermediate: ("Testing Techniques and TDD", "Unit testing: Tests individual functions/methods in isolation. Use mocks/stubs to replace dependencies. Fast to run (milliseconds). Frameworks: JUnit (Java), pytest (Python), Jest (JavaScript). Coverage tools measure what percentage of code is tested.\n\nTest-Driven Development (TDD): Write the test first, then write code to make it pass. Red-Green-Refactor cycle: Write failing test (Red) → Write minimal code to pass (Green) → Refactor for quality (Refactor). Benefits: Forces design thinking, provides regression tests, documents behavior.\n\nIntegration testing: Tests how components interact. Top-down (test high-level components first, stub lower ones), Bottom-up (test low-level components first, build up), Big Bang (integrate all at once — hard to isolate issues).\n\nRegression testing: Re-run tests after changes to ensure nothing broke. Automated regression suites are essential in CI/CD pipelines. Every bug fix should include a regression test."),
                LevelEnum.advanced: ("Advanced Testing: Performance, Security, and Automation", "Performance testing: Load testing (normal load), Stress testing (beyond capacity), Endurance testing (sustained load over time), Spike testing (sudden load increase). Tools: JMeter, Locust, Gatling, k6.\n\nSecurity testing: OWASP Top 10 identifies most critical web vulnerabilities. Penetration testing actively tries to exploit vulnerabilities. Static Application Security Testing (SAST) analyzes source code. Dynamic Application Security Testing (DAST) tests running application. Dependency scanning checks libraries for known CVEs.\n\nBehavior-Driven Development (BDD): Extends TDD with business-readable tests. Given-When-Then format: 'Given [context] When [action] Then [outcome]'. Tools: Cucumber, Behave, SpecFlow. Bridges gap between technical and non-technical stakeholders.\n\nTest automation pyramid: Many unit tests (fast, cheap), fewer integration tests, few end-to-end tests (slow, expensive). Avoid inverted pyramid (few unit tests, many E2E tests) — slow, flaky, expensive. Selenium/Cypress/Playwright for E2E browser automation."),
            },
            "quiz": [
                {"text": "What is the difference between verification and validation?", "option_a": "They are the same thing", "option_b": "Verification checks specifications; validation checks user needs", "option_c": "Validation is done before verification", "option_d": "Verification is done by users", "correct": "B", "explanation": "Verification checks that software matches its specification ('building it right'). Validation checks that it meets actual user needs ('building the right thing')."},
                {"text": "What is the TDD cycle?", "option_a": "Design → Code → Test", "option_b": "Code → Test → Deploy", "option_c": "Red → Green → Refactor", "option_d": "Plan → Implement → Review", "correct": "C", "explanation": "TDD follows the Red-Green-Refactor cycle: Write a failing test (Red), write minimal code to pass it (Green), then refactor for quality while keeping tests green."},
                {"text": "What does black box testing mean?", "option_a": "Testing with complete knowledge of the code", "option_b": "Testing only UI components", "option_c": "Testing based on inputs and expected outputs without knowledge of internals", "option_d": "Testing in a dark environment", "correct": "C", "explanation": "Black box testing treats the system as a black box — tests are designed based on requirements and expected behavior without knowledge of internal implementation."},
                {"text": "What does the testing pyramid recommend?", "option_a": "Mostly end-to-end tests", "option_b": "Equal amounts of all test types", "option_c": "Many unit tests, fewer integration tests, few end-to-end tests", "option_d": "Only manual testing", "correct": "C", "explanation": "The test pyramid recommends many fast unit tests at the base, fewer integration tests in the middle, and few slow end-to-end tests at the top for the best cost/benefit ratio."},
                {"text": "What is regression testing?", "option_a": "Testing old features after adding new ones", "option_b": "Testing new features only", "option_c": "Performance testing", "option_d": "Security testing", "correct": "A", "explanation": "Regression testing re-runs existing tests after code changes to ensure that previously working functionality still works correctly."},
            ]
        },
        {
            "title": "Version Control",
            "content": {
                LevelEnum.foundational: ("Introduction to Version Control", "Version control systems (VCS) track changes to files over time. They allow you to recall specific versions later, see who changed what and when, and collaborate with others without overwriting each other's work.\n\nGit is the most widely used distributed version control system. Created by Linus Torvalds in 2005 for Linux kernel development. Every developer has a complete copy of the repository including full history.\n\nKey concepts: Repository (stores all files and history), Commit (snapshot of changes with a message), Branch (independent line of development), Merge (combining branches), Remote (copy on another server like GitHub).\n\nBasic Git workflow: git init (create repository), git add (stage changes), git commit (save snapshot), git push (upload to remote), git pull (download from remote), git clone (copy remote repository)."),
                LevelEnum.intermediate: ("Branching Strategies and Collaboration", "Branches allow parallel development without interfering with the main codebase. The main/master branch should always be stable and deployable. Feature branches isolate new development. Hotfix branches quickly patch production bugs.\n\nGit Flow: A branching model with main, develop, feature, release, and hotfix branches. Suitable for projects with scheduled releases. More complex but provides clear structure.\n\nGitHub Flow: Simpler — one main branch, feature branches merged via Pull Requests. Deploy immediately after merging. Suitable for continuous deployment teams.\n\nPull Requests (PRs) / Merge Requests (MRs): Propose, review, and discuss changes before merging. Code review catches bugs, enforces standards, and shares knowledge. Automated CI runs tests on every PR. Required approvals before merging maintain code quality.\n\nConflict resolution: When two branches change the same lines differently, Git cannot auto-merge. Developer must manually resolve conflicts, choosing which changes to keep."),
                LevelEnum.advanced: ("Advanced Git and Git Internals", "Git internals: Git stores everything as objects — blobs (file content), trees (directory structure), commits (snapshots with metadata), tags (named commits). Objects are immutable and identified by SHA-1 hash. The .git directory contains the entire repository.\n\nRebase vs Merge: Merge creates a merge commit preserving full history. Rebase replays commits on top of another branch creating linear history. Interactive rebase (git rebase -i) allows squashing, editing, and reordering commits before merging.\n\ngit bisect uses binary search to find the commit that introduced a bug. git blame shows who last modified each line. git stash temporarily saves uncommitted changes.\n\nMonorepo vs Polyrepo: Monorepo stores all code in one repository (Google, Meta approach) — easier cross-project changes, consistent tooling, but complex CI. Polyrepo uses separate repositories per service — simpler individual repos but harder cross-service coordination.\n\nGit hooks: Scripts triggered by Git events (pre-commit, pre-push, post-merge). Used to run linters, tests, and enforce commit message formats before allowing commits."),
            },
            "quiz": [
                {"text": "What is a Git commit?", "option_a": "Uploading code to GitHub", "option_b": "A snapshot of changes saved to the repository", "option_c": "Creating a new branch", "option_d": "Merging two branches", "correct": "B", "explanation": "A Git commit is a snapshot of staged changes saved to the repository with a unique hash, author information, timestamp, and message."},
                {"text": "What is the purpose of a Pull Request?", "option_a": "Download code from a repository", "option_b": "Propose, review, and discuss changes before merging", "option_c": "Create a new repository", "option_d": "Delete a branch", "correct": "B", "explanation": "Pull Requests allow developers to propose changes, have them reviewed by teammates, run automated tests, and discuss before merging into the main branch."},
                {"text": "What does git rebase do?", "option_a": "Creates a merge commit", "option_b": "Deletes commit history", "option_c": "Replays commits on top of another branch creating linear history", "option_d": "Reverts the last commit", "correct": "C", "explanation": "Git rebase replays your commits on top of another branch, creating a linear history without merge commits. Useful for keeping a clean, readable history."},
                {"text": "What command temporarily saves uncommitted changes in Git?", "option_a": "git save", "option_b": "git backup", "option_c": "git stash", "option_d": "git hold", "correct": "C", "explanation": "git stash temporarily saves uncommitted changes to a stack, allowing you to switch branches or pull changes without committing incomplete work."},
                {"text": "What is the main advantage of distributed version control (Git) over centralized?", "option_a": "Better graphical interface", "option_b": "Every developer has a complete copy with full history", "option_c": "Faster internet speed required", "option_d": "Simpler branching", "correct": "B", "explanation": "In distributed VCS like Git, every developer has a complete local copy of the repository including full history, allowing offline work and no single point of failure."},
            ]
        },
        {
            "title": "Agile & Scrum",
            "content": {
                LevelEnum.foundational: ("Introduction to Agile", "Agile is a philosophy for software development that values flexibility, collaboration, and delivering working software frequently. It emerged as a response to the failures of heavyweight, plan-driven methodologies.\n\nThe Agile Manifesto (2001) values: Individuals and interactions over processes and tools. Working software over comprehensive documentation. Customer collaboration over contract negotiation. Responding to change over following a plan.\n\nAgile principles include: Deliver working software frequently (weeks not months), Welcome changing requirements, Business and developers work together daily, Build projects around motivated individuals, Face-to-face conversation is most effective, Working software is the primary measure of progress.\n\nScrum, Kanban, XP (Extreme Programming), and SAFe are frameworks implementing Agile principles. Each has different practices but shares the core Agile values."),
                LevelEnum.intermediate: ("Scrum Framework", "Scrum organizes work in Sprints — fixed-length iterations (1-4 weeks) producing potentially shippable software. Three roles: Product Owner (defines and prioritizes backlog), Scrum Master (facilitates process, removes impediments), Development Team (self-organizing, cross-functional).\n\nScrum artifacts: Product Backlog (ordered list of all desired work), Sprint Backlog (items selected for current sprint), Increment (working software from sprint).\n\nScrum ceremonies: Sprint Planning (team selects and plans sprint work), Daily Scrum/Standup (15-min daily sync: what did I do, what will I do, any blockers), Sprint Review (demo working software to stakeholders), Sprint Retrospective (team reflects on process improvements).\n\nUser stories and story points: Work items written as user stories. Story points estimate relative complexity (not hours). Planning Poker: team estimates independently, then reveals to spark discussion. Velocity: story points completed per sprint — used for forecasting."),
                LevelEnum.advanced: ("Scaling Agile and Advanced Practices", "Kanban: Visualize workflow on a board with columns (To Do, In Progress, Done). Limit WIP (Work in Progress) per column to prevent bottlenecks. Measure cycle time (time from start to done) and throughput. Continuous flow — no sprints. Good for operations and support teams.\n\nSAFe (Scaled Agile Framework): Scales Agile to enterprise level with Program Increments (8-12 weeks), Agile Release Trains (multiple teams), and portfolio management. Complex but provides structure for hundreds of developers.\n\nLeSS (Large-Scale Scrum): Simpler scaling approach — multiple Scrum teams working on one product backlog. One Product Owner, multiple teams. Emphasizes simplicity and reducing organizational complexity.\n\nKPIs for Agile teams: Velocity (story points per sprint), Cycle time (time from start to deployment), Lead time (time from request to delivery), Defect rate, Customer satisfaction. Avoid vanity metrics — focus on outcomes not outputs.\n\nAgile anti-patterns: Dark Scrum (ceremonies without principles), Sprint 0 (planning sprint before development), Waterfall in disguise (upfront design, sequential phases called sprints), Hero culture (relying on individuals not the team)."),
            },
            "quiz": [
                {"text": "What is a Sprint in Scrum?", "option_a": "A long development phase", "option_b": "A fixed-length iteration producing potentially shippable software", "option_c": "A testing phase", "option_d": "A planning meeting", "correct": "B", "explanation": "A Sprint is a fixed-length iteration (typically 1-4 weeks) at the end of which the team produces a potentially shippable product increment."},
                {"text": "What is the Product Owner responsible for?", "option_a": "Managing the development team", "option_b": "Running Scrum ceremonies", "option_c": "Defining and prioritizing the product backlog", "option_d": "Writing all the code", "correct": "C", "explanation": "The Product Owner is responsible for defining, prioritizing, and maintaining the product backlog, ensuring the team works on the highest-value items."},
                {"text": "What happens during a Sprint Retrospective?", "option_a": "Demo working software to stakeholders", "option_b": "Plan the next sprint", "option_c": "Team reflects on process and identifies improvements", "option_d": "Review the product backlog", "correct": "C", "explanation": "The Sprint Retrospective is a meeting where the team reflects on the sprint process and identifies specific improvements to implement in the next sprint."},
                {"text": "What does WIP limit in Kanban prevent?", "option_a": "Too many team members", "option_b": "Bottlenecks from too much simultaneous work in progress", "option_c": "Too many user stories", "option_d": "Frequent deployments", "correct": "B", "explanation": "WIP (Work In Progress) limits prevent too many items from being worked on simultaneously, reducing context switching and exposing bottlenecks in the workflow."},
                {"text": "Which Agile Manifesto value is stated first?", "option_a": "Working software over documentation", "option_b": "Responding to change over following a plan", "option_c": "Individuals and interactions over processes and tools", "option_d": "Customer collaboration over contract negotiation", "correct": "C", "explanation": "The first Agile Manifesto value is 'Individuals and interactions over processes and tools', emphasizing that people and communication matter more than rigid processes."},
            ]
        },
    ]

    # ── Insert OS content ──────────────────────────────
    for mod_data in os_modules_data:
        module = db.query(Module).filter(
            Module.course_id == os_id,
            Module.title     == mod_data["title"],
        ).first()
        if not module:
            print(f"  ⚠️  Module not found: {mod_data['title']}")
            continue

        # Delete existing content and quizzes
        db.query(ModuleContent).filter(ModuleContent.module_id == module.id).delete()
        existing_quiz = db.query(Quiz).filter(Quiz.module_id == module.id).first()
        if existing_quiz:
            db.query(Question).filter(Question.quiz_id == existing_quiz.id).delete()
            db.delete(existing_quiz)
        db.commit()

        # Add content
        for level, (title, body) in mod_data["content"].items():
            db.add(ModuleContent(module_id=module.id, level=level, title=title, body=body, order=1))

        # Add quiz
        quiz = Quiz(module_id=module.id, level=LevelEnum.intermediate, title=f"{mod_data['title']} Quiz")
        db.add(quiz)
        db.flush()
        for q in mod_data["quiz"]:
            db.add(Question(
                quiz_id=quiz.id, text=q["text"],
                option_a=q["option_a"], option_b=q["option_b"],
                option_c=q["option_c"], option_d=q["option_d"],
                correct_option=q["correct"], explanation=q["explanation"],
            ))

        db.commit()
        print(f"  ✓ OS: {mod_data['title']}")

    # ── Insert SE content ──────────────────────────────
    for mod_data in se_modules_data:
        module = db.query(Module).filter(
            Module.course_id == se_id,
            Module.title     == mod_data["title"],
        ).first()
        if not module:
            print(f"  ⚠️  Module not found: {mod_data['title']}")
            continue

        db.query(ModuleContent).filter(ModuleContent.module_id == module.id).delete()
        existing_quiz = db.query(Quiz).filter(Quiz.module_id == module.id).first()
        if existing_quiz:
            db.query(Question).filter(Question.quiz_id == existing_quiz.id).delete()
            db.delete(existing_quiz)
        db.commit()

        for level, (title, body) in mod_data["content"].items():
            db.add(ModuleContent(module_id=module.id, level=level, title=title, body=body, order=1))

        quiz = Quiz(module_id=module.id, level=LevelEnum.intermediate, title=f"{mod_data['title']} Quiz")
        db.add(quiz)
        db.flush()
        for q in mod_data["quiz"]:
            db.add(Question(
                quiz_id=quiz.id, text=q["text"],
                option_a=q["option_a"], option_b=q["option_b"],
                option_c=q["option_c"], option_d=q["option_d"],
                correct_option=q["correct"], explanation=q["explanation"],
            ))

        db.commit()
        print(f"  ✓ SE: {mod_data['title']}")

    print("\n✅ OS and SE courses patched successfully!")
    db.close()

if __name__ == "__main__":
    patch()